from datetime import datetime, timedelta, timezone

_now = datetime.now(timezone.utc)


def _dt(days_ago: int) -> str:
    return (_now - timedelta(days=days_ago)).isoformat()


SEED_LEADS: list[dict] = [
    {
        "id": "a1b2c3d4-0001-0001-0001-000000000001",
        "workspace_id": "mock-workspace-id",
        "name": "Restaurante El Rancho",
        "category": "Gastronomia",
        "location": "San Salvador",
        "address": "Blvd. Los Heroes, San Salvador",
        "latitude": 13.7063,
        "longitude": -89.2055,
        "score": 12,
        "status": "nuevo",
        "priority": "alta",
        "issues": ["Sin sitio web", "Sin telefono registrado", "Perfil de Google Business incompleto"],
        "phone": None,
        "website": None,
        "google_place_id": "ChIJ-mock-0001",
        "source": "explorer",
        "last_contact": None,
        "created_at": _dt(5),
        "updated_at": _dt(5),
    },
    {
        "id": "a1b2c3d4-0002-0002-0002-000000000002",
        "workspace_id": "mock-workspace-id",
        "name": "Farmacia San Jose",
        "category": "Salud",
        "location": "Santa Tecla",
        "address": "4a Av. Sur #12, Santa Tecla",
        "latitude": 13.6762,
        "longitude": -89.2813,
        "score": 25,
        "status": "contactado",
        "priority": "media",
        "issues": ["Sin sitio web", "Rendimiento web bajo"],
        "phone": "+503 2228-1234",
        "website": None,
        "google_place_id": "ChIJ-mock-0002",
        "source": "explorer",
        "last_contact": _dt(2)[:10],
        "created_at": _dt(10),
        "updated_at": _dt(2),
    },
    {
        "id": "a1b2c3d4-0003-0003-0003-000000000003",
        "workspace_id": "mock-workspace-id",
        "name": "Auto Repuestos Martinez",
        "category": "Automotriz",
        "location": "Soyapango",
        "address": "Carretera Panamericana km 8, Soyapango",
        "latitude": 13.7086,
        "longitude": -89.1432,
        "score": 15,
        "status": "nuevo",
        "priority": "alta",
        "issues": ["Sin sitio web", "Sin calificaciones", "Perfil de Google Business incompleto"],
        "phone": "+503 2295-5678",
        "website": None,
        "google_place_id": "ChIJ-mock-0003",
        "source": "manual",
        "last_contact": None,
        "created_at": _dt(3),
        "updated_at": _dt(3),
    },
    {
        "id": "a1b2c3d4-0004-0004-0004-000000000004",
        "workspace_id": "mock-workspace-id",
        "name": "Boutique Luna",
        "category": "Retail",
        "location": "Antiguo Cuscatlan",
        "address": "C.C. La Gran Via, Antiguo Cuscatlan",
        "latitude": 13.6784,
        "longitude": -89.2571,
        "score": 38,
        "status": "calificado",
        "priority": "media",
        "issues": ["Sitio web sin SSL", "Rendimiento web bajo"],
        "phone": "+503 2243-9000",
        "website": "http://boutiqueluna.com.sv",
        "google_place_id": "ChIJ-mock-0004",
        "source": "explorer",
        "last_contact": _dt(1)[:10],
        "created_at": _dt(15),
        "updated_at": _dt(1),
    },
    {
        "id": "a1b2c3d4-0005-0005-0005-000000000005",
        "workspace_id": "mock-workspace-id",
        "name": "Hotel Casa Blanca",
        "category": "Turismo",
        "location": "Santa Ana",
        "address": "25 Av. Norte #5, Santa Ana",
        "latitude": 13.9946,
        "longitude": -89.5597,
        "score": 45,
        "status": "contactado",
        "priority": "baja",
        "issues": ["Rendimiento web bajo"],
        "phone": "+503 2440-1111",
        "website": "https://hotelcasablanca.com.sv",
        "google_place_id": "ChIJ-mock-0005",
        "source": "explorer",
        "last_contact": _dt(4)[:10],
        "created_at": _dt(20),
        "updated_at": _dt(4),
    },
    {
        "id": "a1b2c3d4-0006-0006-0006-000000000006",
        "workspace_id": "mock-workspace-id",
        "name": "Instituto Tecnico Colon",
        "category": "Educacion",
        "location": "San Salvador",
        "address": "Alameda Roosevelt #324, San Salvador",
        "latitude": 13.6994,
        "longitude": -89.2157,
        "score": 8,
        "status": "nuevo",
        "priority": "alta",
        "issues": ["Sin sitio web", "Sin telefono registrado", "Sin calificaciones", "Perfil de Google Business incompleto"],
        "phone": None,
        "website": None,
        "google_place_id": "ChIJ-mock-0006",
        "source": "manual",
        "last_contact": None,
        "created_at": _dt(1),
        "updated_at": _dt(1),
    },
    {
        "id": "a1b2c3d4-0007-0007-0007-000000000007",
        "workspace_id": "mock-workspace-id",
        "name": "Taller El Maestro",
        "category": "Automotriz",
        "location": "San Miguel",
        "address": "Calle Sirama #8, San Miguel",
        "latitude": 13.4794,
        "longitude": -88.1827,
        "score": 20,
        "status": "nuevo",
        "priority": "alta",
        "issues": ["Sin sitio web", "Sin calificaciones"],
        "phone": "+503 2661-4321",
        "website": None,
        "google_place_id": "ChIJ-mock-0007",
        "source": "explorer",
        "last_contact": None,
        "created_at": _dt(7),
        "updated_at": _dt(7),
    },
    {
        "id": "a1b2c3d4-0008-0008-0008-000000000008",
        "workspace_id": "mock-workspace-id",
        "name": "Consultorio Dr. Ramirez",
        "category": "Salud",
        "location": "Antiguo Cuscatlan",
        "address": "Calle El Pedregal #45, Antiguo Cuscatlan",
        "latitude": 13.6720,
        "longitude": -89.2490,
        "score": 55,
        "status": "calificado",
        "priority": "baja",
        "issues": ["Rendimiento web bajo"],
        "phone": "+503 2278-6789",
        "website": "https://drramirez.com.sv",
        "google_place_id": "ChIJ-mock-0008",
        "source": "manual",
        "last_contact": _dt(3)[:10],
        "created_at": _dt(25),
        "updated_at": _dt(3),
    },
    {
        "id": "a1b2c3d4-0009-0009-0009-000000000009",
        "workspace_id": "mock-workspace-id",
        "name": "Supermercado Familiar",
        "category": "Retail",
        "location": "Soyapango",
        "address": "Blvd. del Ejercito #120, Soyapango",
        "latitude": 13.7155,
        "longitude": -89.1523,
        "score": 18,
        "status": "nuevo",
        "priority": "alta",
        "issues": ["Sin sitio web", "Perfil de Google Business incompleto"],
        "phone": "+503 2277-3456",
        "website": None,
        "google_place_id": "ChIJ-mock-0009",
        "source": "explorer",
        "last_contact": None,
        "created_at": _dt(2),
        "updated_at": _dt(2),
    },
    {
        "id": "a1b2c3d4-0010-0010-0010-000000000010",
        "workspace_id": "mock-workspace-id",
        "name": "Agencia de Viajes Paraiso",
        "category": "Turismo",
        "location": "San Salvador",
        "address": "89 Av. Norte #15, San Salvador",
        "latitude": 13.7020,
        "longitude": -89.2210,
        "score": 30,
        "status": "contactado",
        "priority": "media",
        "issues": ["Sitio web sin SSL", "Sin calificaciones"],
        "phone": "+503 2263-8080",
        "website": "http://viajesparaiso.com",
        "google_place_id": "ChIJ-mock-0010",
        "source": "explorer",
        "last_contact": _dt(6)[:10],
        "created_at": _dt(12),
        "updated_at": _dt(6),
    },
    {
        "id": "a1b2c3d4-0011-0011-0011-000000000011",
        "workspace_id": "mock-workspace-id",
        "name": "Libreria El Estudiante",
        "category": "Educacion",
        "location": "Santa Ana",
        "address": "3a Calle Poniente #22, Santa Ana",
        "latitude": 13.9978,
        "longitude": -89.5562,
        "score": 22,
        "status": "nuevo",
        "priority": "media",
        "issues": ["Sin sitio web", "Sin calificaciones"],
        "phone": "+503 2441-2233",
        "website": None,
        "google_place_id": "ChIJ-mock-0011",
        "source": "manual",
        "last_contact": None,
        "created_at": _dt(8),
        "updated_at": _dt(8),
    },
    {
        "id": "a1b2c3d4-0012-0012-0012-000000000012",
        "workspace_id": "mock-workspace-id",
        "name": "Pupuseria Dona Carmen",
        "category": "Gastronomia",
        "location": "Santa Tecla",
        "address": "Av. Masferrer Norte #8, Santa Tecla",
        "latitude": 13.6810,
        "longitude": -89.2790,
        "score": 10,
        "status": "perdido",
        "priority": "alta",
        "issues": ["Sin sitio web", "Sin telefono registrado", "Sin calificaciones"],
        "phone": None,
        "website": None,
        "google_place_id": "ChIJ-mock-0012",
        "source": "explorer",
        "last_contact": _dt(14)[:10],
        "created_at": _dt(30),
        "updated_at": _dt(14),
    },
    {
        "id": "a1b2c3d4-0013-0013-0013-000000000013",
        "workspace_id": "mock-workspace-id",
        "name": "Ferreteria Construmax",
        "category": "Servicios",
        "location": "San Salvador",
        "address": "Calle Modelo #67, San Salvador",
        "latitude": 13.6953,
        "longitude": -89.1980,
        "score": 42,
        "status": "calificado",
        "priority": "baja",
        "issues": ["Sitio web sin SSL"],
        "phone": "+503 2222-7777",
        "website": "http://construmax.com.sv",
        "google_place_id": "ChIJ-mock-0013",
        "source": "manual",
        "last_contact": _dt(5)[:10],
        "created_at": _dt(18),
        "updated_at": _dt(5),
    },
    {
        "id": "a1b2c3d4-0014-0014-0014-000000000014",
        "workspace_id": "mock-workspace-id",
        "name": "Spa Serenidad",
        "category": "Servicios",
        "location": "Antiguo Cuscatlan",
        "address": "Calle Las Mercedes #12, Antiguo Cuscatlan",
        "latitude": 13.6801,
        "longitude": -89.2530,
        "score": 16,
        "status": "nuevo",
        "priority": "alta",
        "issues": ["Sin sitio web", "Sin calificaciones", "Perfil de Google Business incompleto"],
        "phone": "+503 2289-4567",
        "website": None,
        "google_place_id": "ChIJ-mock-0014",
        "source": "explorer",
        "last_contact": None,
        "created_at": _dt(0),
        "updated_at": _dt(0),
    },
    {
        "id": "a1b2c3d4-0015-0015-0015-000000000015",
        "workspace_id": "mock-workspace-id",
        "name": "Moto Repuestos Express",
        "category": "Automotriz",
        "location": "San Miguel",
        "address": "Av. Roosevelt Sur #34, San Miguel",
        "latitude": 13.4822,
        "longitude": -88.1795,
        "score": 35,
        "status": "contactado",
        "priority": "media",
        "issues": ["Sitio web sin SSL", "Sin calificaciones"],
        "phone": "+503 2660-9988",
        "website": "http://motoexpress.com",
        "google_place_id": "ChIJ-mock-0015",
        "source": "explorer",
        "last_contact": _dt(3)[:10],
        "created_at": _dt(11),
        "updated_at": _dt(3),
    },
]
